name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./app/app-release.apk
